### ISSUE TITLE
Progress should be saved when user exits lightbox

### ISSUE THREAD

**Issue by kevinthewebguy** [wynnset/tapestry-d3#75]
Right now, there's a 5 second delay for sending save progress requests while watching the video. There should be a progress save fire when the user exits the lightbox (video player).

**Comment by kevinthewebguy** [comment]
Since this seems to conflict with what Ford is working on (adding unlocked to user progress). I can get him to double check if this issue persists and if it does I can debug it further with the new changes.

**Comment by wynnset** [comment]
We are ok with the progress being saved within a 5 second margin, so I'll close this issue.
