### ISSUE TITLE
Root node disappears when traversed from

### ISSUE THREAD

**Issue by fordat** [wynnset/tapestry-d3#76]
When you traverse to another node, occasionally the root node disappears. I made a tapestry titled `d3 testing` that it can be seen on – I'm not sure if this can be accessed from the database. On other tapestries I've worked with today the bug is not present; but it's appeared a handful of times before now.

**Comment by fordat** [comment]
it's present on another tapestry I've made called `bonsai 2`. Here:

![Screen Shot 2019-07-10 at 2 35 39 PM](https://user-images.githubusercontent.com/13429272/61006791-033b2700-a320-11e9-8edc-f2bd404fc7a3.png)

**Comment by wynnset** [comment]
Can you please verify if this bug still exists?

**Comment by wynnset** [comment]
I believe this is fixed so I'm going to close it. Please reopen if you find it's not fixed @fordat
