### ISSUE TITLE
Delete existing nodes and links

### ISSUE THREAD

**Issue by wynnset** [wynnset/tapestry-d3#86]
Delete node (need to have edit permission):
- On Edit Node pop-up, add a button to Delete the node

Delete link (need to have edit permission):
- Check the link to see if there will be a path from root node to the nodes that this link is connected to. If there is, then this link is editable. Only do this if the link is editable:
- When hovering over a link, the link becomes red
- If you click on the link and confirm you want to delete this link, the link gets deleted

**Comment by kevinthewebguy** [comment]
I duplicated this issue. Will be removing this one since I have branches and PR set up for the other issue.
