### ISSUE TITLE
Text node popup is blank

### ISSUE THREAD

**Issue by kevinthewebguy** [wynnset/tapestry-d3#96]
Steps to reproduce:
1. Create a text node
2. Click on the media button 
3. Exit out of the text node popup
4. Repeat 2 and 3 if you can't see the bug

Observed behavior:
Blank popup
Expected behavior:
Always show text node

**Comment by wynnset** [comment]
@kevinthewebguy I cannot replicate this issue. Are you on the latest version of master?

**Comment by kevinthewebguy** [comment]
Cannot reproduce now. Closing issue.
